#! /bin/bash

/usr/sbin/hdparm -C $@ | {
    declare -A targets
    drive=
    while read line
    do
	if echo "${line}" | /usr/bin/grep /dev/ >/dev/null 2>&1; then
	    drive="${line%:*}"
	    drive="${drive#/dev/}"
	elif echo "${line}" | /usr/bin/grep "state is:" > /dev/null 2>&1 ; then
	    value=${line##*:}
	    targets["${drive}"]=${value#  }
	else
	   drive=
	fi   
    done

    echo "{"
    for target in "${!targets[@]}"
    do
	echo "  \"$target\": {"
	if ! (echo "${targets[$target]}" | /usr/bin/grep "standby") > /dev/null 2>&1; then
	    /usr/sbin/smartctl -A /dev/$target |/usr/bin/grep "^ *[0-9]" | /usr/bin/awk '{print "    \"" $2 "\":" $10 ","}'
	fi
	echo "    \"state\": \"${targets[$target]}\""
	echo "  },"
    done
    echo '  "__dummy__":{}'
    echo "}"
}
