#! /bin/bash

echo "{"
LAST=""
for target
do
    if [ -n "$LAST" ]; then
	echo "${LAST}",
	LAST=""
    fi
    STATUS=$(/usr/sbin/hdparm -C "/dev/${target}" \
		 | /usr/bin/grep "state is:" \
		 | cut -c 19-)
    echo "  \"$target\": {"
    if [ "S{STATUS}" = "standby" ]; then
	echo '    "state": "standby"'
    else
	/usr/sbin/smartctl -A /dev/$target \
	    | /usr/bin/grep "^ *[0-9]" \
	    | /usr/bin/sed -e 's/\([0-9]*\)h.*m.*s$/\1/' \
	    | /usr/bin/awk '{print "    \"" $2 "\":" $10 ","}'
	echo "   \"state\": \"${targets[$target]}\""
    fi
    LAST="  }"
done
echo "$LAST"
echo "}"
