#! /bin/bash

TYPES=$(smartctl --scan)

echo "{"
LAST=""
for target
do
    if [ -n "$LAST" ]; then
	echo "${LAST}",
	LAST=""
    fi
    if grep "${target} -d sat" > /dev/null 2>&1 ; then
	# If the device type is identified as 'sat'(=SATA), in many case it's connected with USB-SATA bridge now. The I/F doesn't handle hdparm status.
	IO=$(iostat -o JSON  sdb sd{d..l} | jq '.sysstat.hosts[0].statistics[0].disk[] | select(.disk_device=="sde").tps')
	if [ "$IO" -gt 0 ]; then
	    STATUS="active"
	else
	    STATUS="standby"
	fi
    else
	STATUS=$(/usr/sbin/hdparm -C "/dev/${target}" \
		 | /usr/bin/grep "state is:" \
		 | cut -c 19-)
    fi
    echo "  \"$target\": {"
    if [ "S{STATUS}" = "standby" ]; then
	echo '    "state": "standby"'
    else
	/usr/sbin/smartctl -A /dev/$target \
	    | /usr/bin/grep "^ *[0-9]" \
	    | /usr/bin/sed -e 's/\([0-9]*\)h.*m.*s$/\1/' \
	    | /usr/bin/awk '{print "    \"" $2 "\":" $10 ","}'
	echo "   \"state\": \"${targets[$target]}\""
    fi
    LAST="  }"
done
echo "$LAST"
echo "}"
