#! /bin/bash

TARGET="$1"
WAIT_FOR_VALUE="$2" # wait for writing from process
if [ -z "${WAIT_FOR_VALUE}" ]; then
  WAIT_FOR_VALUE=3
fi

if [ ! -e "${TARGET}" ]; then
   # no file error
   exit 1
fi
# read values from file
for ((i=0; i<${WAIT_FOR_VALUE}; i++))
do
   RESULT=$(cat ${TARGET})
   if [ -n "${RESULT}" ] ; then
      echo "${RESULT}"
      exit 0
   fi
   sleep 1
done
# no value
exit 2
